/**
 * Tree-shake setup do Lucide.
 *
 * Quando adicionar um data-lucide="novo-icone" novo no projeto, importe o ícone
 * aqui em PascalCase (ex: <i data-lucide="circle-dot"> → import { CircleDot }).
 *
 * Se um ícone usado no HTML não estiver listado aqui, ele simplesmente não
 * renderiza (sem quebrar a página). Para auditar, rode:
 *   rg 'data-lucide="([a-z0-9-]+)"' -or '$1' --no-filename | sort -u
 */
import {
    createIcons,
    AlertCircle,
    AlignLeft,
    ArrowDown,
    ArrowLeft,
    ArrowRight,
    ArrowUp,
    BookOpen,
    Braces,
    Calendar,
    CalendarPlus,
    CheckCircle,
    ChevronDown,
    CircleAlert,
    CircleCheck,
    CircleDot,
    Clock,
    CloudUpload,
    Code,
    Copy,
    Download,
    ExternalLink,
    Eye,
    FileArchive,
    FileText,
    Fingerprint,
    Gauge,
    Globe,
    HelpCircle,
    Home,
    IdCard,
    Image,
    IndentDecrease,
    IndentIncrease,
    Infinity as InfinityIcon,
    Keyboard,
    Layers,
    LineChart,
    Link,
    List,
    ListOrdered,
    ListX,
    Lock,
    Mail,
    MailOpen,
    MapPin,
    MessageCircle,
    MessageCircleQuestion,
    Minimize2,
    Minus,
    Palette,
    Percent,
    Plus,
    RefreshCw,
    RotateCcw,
    Rss,
    Ruler,
    Search,
    Server,
    Share2,
    Shield,
    Sparkles,
    Star,
    Sword,
    Trash2,
    TrendingDown,
    TrendingUp,
    Type,
    Unlock,
    Wrench,
    X,
    Zap,
} from "lucide";

const icons = {
    AlertCircle,
    AlignLeft,
    ArrowDown,
    ArrowLeft,
    ArrowRight,
    ArrowUp,
    BookOpen,
    Braces,
    Calendar,
    CalendarPlus,
    CheckCircle,
    ChevronDown,
    CircleAlert,
    CircleCheck,
    CircleDot,
    Clock,
    CloudUpload,
    Code,
    Copy,
    Download,
    ExternalLink,
    Eye,
    FileArchive,
    FileText,
    Fingerprint,
    Gauge,
    Globe,
    HelpCircle,
    Home,
    IdCard,
    Image,
    IndentDecrease,
    IndentIncrease,
    Infinity: InfinityIcon,
    Keyboard,
    Layers,
    LineChart,
    Link,
    List,
    ListOrdered,
    ListX,
    Lock,
    Mail,
    MailOpen,
    MapPin,
    MessageCircle,
    MessageCircleQuestion,
    Minimize2,
    Minus,
    Palette,
    Percent,
    Plus,
    RefreshCw,
    RotateCcw,
    Rss,
    Ruler,
    Search,
    Server,
    Share2,
    Shield,
    Sparkles,
    Star,
    Sword,
    Trash2,
    TrendingDown,
    TrendingUp,
    Type,
    Unlock,
    Wrench,
    X,
    Zap,
};

export function renderIcons(root) {
    createIcons({ icons, root });
}

// Compatibilidade: tools que chamam `lucide.createIcons()` direto
// (como image-compressor.js após injetar HTML) continuam funcionando.
if (typeof window !== "undefined") {
    window.lucide = {
        createIcons: (opts = {}) => createIcons({ icons, ...opts }),
    };
}
